// @ts-check
// Regenerate lib/db/database.types.ts from a live database (S4).
//
//   npm run db:types
//
// Runs `supabase gen types typescript --db-url …` (the CLI downloads its
// binary on first use and runs Supabase's postgres-meta image in Docker) and
// prepends the provenance header. Defaults to the local compose database;
// DATABASE_URL overrides it. Re-run after any migration — the generated file
// is committed, and `supabase/tests/api.test.ts` fails if the `entries`
// columns drift from the Zod schema that consumes them.

import { spawnSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const DEFAULT_URL = "postgresql://postgres:postgres@127.0.0.1:54322/postgres";
const OUTPUT = fileURLToPath(new URL("../../lib/db/database.types.ts", import.meta.url));

const url = process.env.DATABASE_URL ?? DEFAULT_URL;
const host = new URL(url).hostname;
if (host !== "127.0.0.1" && host !== "localhost") {
  console.warn(`db:types: generating from a non-local database (${host})`);
}

const result = spawnSync(
  "npx",
  ["supabase@latest", "gen", "types", "typescript", "--db-url", url, "--schema", "public"],
  { encoding: "utf8", stdio: ["ignore", "pipe", "inherit"], maxBuffer: 16 * 1024 * 1024 },
);
if (result.status !== 0 || !result.stdout.includes("export type Database")) {
  console.error("db:types: generation failed");
  process.exit(result.status || 1);
}

const header = `// GENERATED by \`npm run db:types\` (scripts/db/types.mjs) — do not edit.
//
// Source of truth: supabase/migrations/*.sql. This file gives supabase-js the
// \`Database\` generic so column names and embedded relations are checked at
// compile time; runtime shape and the closed kind/facet value sets live in
// lib/content/schema.ts (Zod). Re-run after any migration.

`;

writeFileSync(OUTPUT, header + result.stdout);
console.log(`db:types: wrote ${OUTPUT}`);
